services:
  backend:
    build: ./backend
    environment:
      - MUSIC_DIR=/music_files
      - FRONTEND_ORIGIN=http://localhost
    volumes:
      - ./backend/src:/app
      - music_files:/music_files
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:8000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  music_files:
