services:
  backend:
    build: ./backend
    environment:
      - FRONTEND_ORIGIN=http://localhost
    volumes:
      - ./backend/src:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:8000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    ports:
      - "80:80"
    depends_on:
      - backend
